"""add conversation_turns free_text_labels answer_labels demographic_weights

Revision ID: bf0a3c0a9e22
Revises: eb5c69f8fc34
Create Date: 2026-06-23 17:07:21.910287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0a3c0a9e22'
down_revision: Union[str, None] = 'eb5c69f8fc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
