"""add_ner_freetext_crosssurvey_factcheck

Revision ID: cdf312f9173a
Revises: bf0a3c0a9e22
Create Date: 2026-06-23 18:16:37.215537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf312f9173a'
down_revision: Union[str, None] = 'bf0a3c0a9e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
